---
title: "Hello, Penguins!"
author: "Sebastian Camilo Loos"
format: html
editor: visual
execute: 
  warning: false
---

## Data

For this analysis we'll use the penguins dataset from the palmerpenguins R package.

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(ggthemes)
library(palmerpenguins)
library(gt)
```

## Species

The figure below is a scatterplot of species of penguins.

```{r}
#| label: bill-dims-species
#| warning: false
#| fig-width: 5
#| fig-asp: 0.618

ggplot(data = penguins,
       mapping = aes(x = bill_length_mm, 
                     y = bill_depth_mm,
                     color = species,
                     shape = species)) +
  geom_point() +
  scale_color_colorblind() +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)") +
  theme_minimal()
```

## Flipper Histogram

```{r}
#| label: flipper-histogtam
#| message: false
flipper_hist <- ggplot(data = penguins, aes(x = flipper_length_mm)) +
  geom_histogram(aes(fill = species), 
                 alpha = 0.5, 
                 position = "identity") +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  labs(x = "Flipper length (mm)",
       y = "Frequency",
       title = "Penguin flipper lengths")
flipper_hist
```

## Penguins

The table below shows the first 10 penguins from the dataset.

```{r}
#| label: penguins-top10
#| echo: false

penguins |>
  slice_head(n = 10) |>
  select(species, island, bill_length_mm, bill_depth_mm) |>
  gt()
```
